### ISSUE TITLE
Load a pretrained BERT model giving error

### ISSUE THREAD

**Issue by Vincentchhsu** [facebookresearch/TaBERT#11]
Hi, when i  use TableBertModel.from_pretrained to load a model (/tabert_base_k1/model.bin) but it return below error : 

```
Traceback (most recent call last):
  File "tabert.py", line 1, in <module>
    from table_bert import TableBertModel
  File "/var/Project/SmartSearch/TableQA/TaBERT-master/table_bert/__init__.py", line 8, in <module>
    from table_bert.config import TableBertConfig
  File "/var/Project/SmartSearch/TableQA/TaBERT-master/table_bert/config.py", line 34, in <module>
    type_vocab_size=2,
TypeError: __init__() got an unexpected keyword argument 'layer_norm_eps'
```

would you please tell me how to solve this problem? thanks.

**Comment by hyukyu** [comment]
same error happened to me when I installed pytorch-pretrained-bert directly from pip.
try reinstalling the package using `pip install --editable=git+https://github.com/huggingface/transformers.git@372a5c1ceec49b52c503707e9657bfaae7c236a0#egg=pytorch_pretrained_bert`
