### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.prepare_training_data'

### ISSUE THREAD

**Issue by akshatabhat** [facebookresearch/TaBERT#19]
I am trying to run generate_vanilla_tabert_training_data.sh, however, I get this error -

Traceback (most recent call last):
  File "/opt/conda/envs/tabert/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/tabert/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tabert/utils/generate_vanilla_tabert_training_data.py", line 42, in <module>
    from utils.prepare_training_data import sample_context
ModuleNotFoundError: No module named 'utils.prepare_training_data'

Am I missing something, or is the file "prepare_training_data.py'" missing from the repo?

**Comment by Zhangquxnsad** [comment]
I have the same issue

**Comment by Zhangquxnsad** [comment]
You can replace the “from utils.prepare_training_data import sample_context" into the "from generate_vertical_tabert_training_data  import sample_context".

**Comment by ASEXPIAO** [comment]
> You can replace the “from utils.prepare_training_data import sample_context" into the "from generate_vertical_tabert_training_data import sample_context".

You may encounter a "ModuleNotFoundError: No module named 'generate_vertical_tabert_training_data'" error. In that case, please modify the line "from generate_vertical_tabert_training_data import sample_context" to "from utils.generate_vertical_tabert_training_data import sample_context".
